name: soccer-booking-app
services:
  user-service:
    container_name: user-service
    # image: frdausa/user-service:1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - .env